### ISSUE TITLE
Fonts on the site

### ISSUE THREAD

**Issue by mpbixal** [Bixal/bixal-site-drupal#125]
> Are we using Bixal brand fonts, or alternate fonts? I assume alternate. 

> Instances of Georgia need to have tighter leading than Helvetica Neue 

@mejiaj are the fonts on the site consistent? Are they loading properly on the Drupal implementation?

**Comment by mejiaj** [comment]
@mpbixal font from typekit (Novel Pro [header] & Proxima Nova [body]) seems to be loading.

I _do_ see a 404 on the USWDS font source sans pro, but we're not using it. Looks like that's being set in a USWDS style for the `.usa-prose` class. We should fix that.

**Comment by mattsqd** [comment]
@mejiaj  here's what we did https://github.com/Bixal/bixal-site-drupal/pull/211
* Added the font files that were 404'n
* Removed the `usa-prose` class from the body since it's not in story book.

**Comment by mejiaj** [comment]
We shouldn't be using `usa-prose` since it includes a lot of overrides. If we want to improve readability we should create our own class for it.

I still see it on the homepage:
![image](https://github.com/user-attachments/assets/64927b18-d641-4989-9ba6-da21480f6c80)

**Comment by mattsqd** [comment]
Thanks @mejiaj ! That makes sense. This change has not been deployed to prod yet.
