### ISSUE TITLE
Bixaler: When creating a term from a term reference field, putting parenthesis around content stops the page from being saved

### ISSUE THREAD

**Issue by mpbixal** [Bixal/bixal-site-drupal#171]
For example, `User Experience (UX)` was attempted to be added as a specialty.

https://www.drupal.org/project/autocomplete_deluxe

**Comment by mpbixal** [comment]
This issue is captured for autocomplete deluxe here https://www.drupal.org/project/autocomplete_deluxe/issues/3178337
and for drupal core here https://www.drupal.org/project/drupal/issues/2924783#comment-14062515

**Comment by buddy-harlow** [comment]
@mpbixal Submitted a PR for this one yesterday!
