### ISSUE TITLE
Add support for embed an external HLS video

### ISSUE THREAD

**Issue by mattsqd** [Bixal/bixal-site-drupal#298]
Will come from https://docs.aws.amazon.com/mediastore/latest/ug/cdns-allowing-cloudfront-to-access-mediastore.html.
An example from last year: https://d474nuifpska.cloudfront.net/holiday-special.m3u8
Best case is to allow this as a media type so it can be embedded in the body of any content.

**Comment by mattsqd** [comment]
https://www.drupal.org/project/videojs seems to support this, but it might only be a local m3u8 file.

**Comment by mejiaj** [comment]
@mattsqd is the `m3u8` format the best (quality/performance) for HLS video?

Thinking of this similar to how we favored WEBP over traditional formats.

**Comment by mattsqd** [comment]
> @mattsqd is the `m3u8` format the best (quality/performance) for HLS video?
> 
> Thinking of this similar to how we favored WEBP over traditional formats.

I'm not sure, I'm just going based on the previous year's Christmas party stream. This was a request from John Franklin. 
What is the preferred format for streaming?

**Comment by mattsqd** [comment]
Thanks for the resources @mejiaj ! I'll pass this along.

**Comment by jlfranklin** [comment]
We're using HLS because it's supported by AWS MediaLive and allows for "live" streaming.  That is, no matter when you start watching the stream, you'll be watching the same point (plus or minus about 6 seconds) as everyone else.
