### ISSUE TITLE
bixal-site-drupal - feature request: Add 'Drupal Certified Partner badge' badge to the footer

### ISSUE THREAD

**Issue by mattsqd** [Bixal/bixal-site-drupal#303]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
'Drupal Certified Partner badge' icon in the footer.

**Describe alternatives you've considered**
Possibly make the block of images editorially controlled for self-service.

**Additional context**
This is a code change, only the menus in the footer are editorially controlled.

**Comment by mattsqd** [comment]
![drupal_certified_bronze_partner](https://github.com/user-attachments/assets/91e8d9ad-05f5-4279-b94f-e362b2defbe2)
![drupal_certified_bronze_partner](https://github.com/user-attachments/assets/a11db1d2-53df-4999-9849-8e7a4adf07af)

**Comment by mejiaj** [comment]
We should use the SVG version (2nd one) wherever possible.

**Comment by mattsqd** [comment]
![image](https://github.com/user-attachments/assets/f53437df-ff11-41e2-bfb1-781ac4502f82)
