### ISSUE TITLE
Description list image is missing the vertical line on images while logged in 

### ISSUE THREAD

**Issue by mpbixal** [Bixal/bixal-site-drupal#77]
See https://github.com/Bixal/bixal-site-drupal/pull/72#issuecomment-1936072160

**Comment by mpbixal** [comment]
@mejiaj can you let me know what approach would work best here?

**Comment by mejiaj** [comment]
@mpbixal does it go away if you add the following CSS:

```diff
.bix-description-list__media {
    position: relative;
+   z-index: 1;
}
```
